---
name: Catalyst-Model-Estraier
version: 0.0.1
author:
  - 'Takeru INOUE <takeru.inoue _ gmail.com>'
abstract: Hyper Estraier model class for Catalyst
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Catalyst::Helper: 0
  FindBin: 0
  Search::Estraier: 0
  Test::More: 0
  version: 0
provides:
  Catalyst::Helper::Model::Estraier:
    file: lib/Catalyst/Helper/Model/Estraier.pm
  Catalyst::Model::Estraier:
    file: lib/Catalyst/Model/Estraier.pm
    version: 0.0.1
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
